apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ora-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: ora-pv-volume
