apiVersion: v1
kind: PersistentVolume
metadata:
  name: ora-pv-volume
labels:
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /fnvol/oradata/default
    server: 10.57.149.250
