# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-db
spec:
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      volumes:
        - name: postgres-pv-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      containers:
        - name: postgresql-db
          image: postgres:12
          volumeMounts:
            - name: postgres-pv-storage
              mountPath: /fnvol
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: cEBzc3dvcmQxMgo=
            - name: PGDATA
              value: /fnvol/PGDATA
      