apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
labels:
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /fnvol
    server: 10.57.149.250