apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service-ext
spec:
  ports:
    - port: 5432
  selector:
    app: postgresql-db
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
