apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmis-cfgstore
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cmis-cfgstore-pv
  volumeName: cmis-cfgstore-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
