apiVersion: v1
kind: PersistentVolume
metadata:
  name: cmis-logstore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /fnvol/hsbc-867330-ecmwf-dev/default/cfgstore/cmis/logs
    server: 10.57.149.250
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cmis-logstore-pv
