apiVersion: v1
kind: PersistentVolume
metadata:
  name: cpe-textext-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /fnvol/hsbc-867330-ecmwf-dev/default/cfgstore/cpe/textext
    server: 10.57.149.250
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cpe-textext-pv
