apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: cp4a-shared-log-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /fnvol/operator-logs
    server: 10.57.149.250
  persistentVolumeReclaimPolicy: Delete
