apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: operator-shared-pv
spec:
   capacity:
     storage: 1Gi
   accessModes:
   - ReadWriteMany
   nfs:
     path: /fnvol/operator
     server: 10.57.149.250
   persistentVolumeReclaimPolicy: Delete
